require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const data = [
  {
    "id": 13,
    "process": "QFD Availity Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.25,
    "manual_fte": 2.0,
    "last_run_date": "2026-03-02",
    "last_run_count": 1083,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 7,
    "process": "QFD File Creation Billing Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.7,
    "manual_fte": 0.5,
    "last_run_date": "2026-05-04",
    "last_run_count": 69,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 27,
    "process": "QFD Denial Tracking Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Bimsara"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-10-10",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 18,
    "process": "US Neuro Encoder Pro Billing Automation",
    "data": {},
    "type": "Automation",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.8,
    "manual_fte": 0.4,
    "last_run_date": "2026-01-20",
    "last_run_count": 41,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 36,
    "process": "Mind Sync LLC -  Patient Financial Services macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-05-22",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 4,
    "process": "Neuro Surg Appeal Creation Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.7,
    "manual_fte": 0.3,
    "last_run_date": "2026-04-28",
    "last_run_count": 16,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 22,
    "process": "IDR Analytics Dashboard",
    "data": {},
    "type": "Software Development",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Amila"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-03-30",
    "deadline": "2026-04-20",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [
      "Development Testing"
    ],
    "demo_video": "demo_22_1777297723289.mp4",
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha",
      "Chamath"
    ]
  },
  {
    "id": 15,
    "process": "TSH Availity Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.2,
    "manual_fte": 0.2,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 29,
    "process": "QFD Panel Report Automation",
    "data": {},
    "type": "Automation",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 0.4,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-12-18",
    "deadline": "2025-12-26",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "IQ",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "In Progress",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 14,
    "process": "US Neuro Availity Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production-Hold",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.5,
    "manual_fte": 2.5,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 21,
    "process": "Denail Management Chatbot /Assistance",
    "data": {},
    "type": "Software Development",
    "status": "Developing",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Vihanga"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-04-01",
    "deadline": "2026-04-20",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 37,
    "process": "NeuroSurge LLC -  Patient Financial Services macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-05-22",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 2,
    "process": "US Neuro Appeal Creation Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2025-12-17",
    "deadline": "2026-04-20",
    "frequency": "Daily",
    "auto_fte": 3.0,
    "manual_fte": 1.0,
    "last_run_date": "2026-05-04",
    "last_run_count": 100,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 24,
    "process": "Collective IQ Production Evaluation Dashboard",
    "data": {},
    "type": "Software Development",
    "status": "Developing",
    "completion": 0.85,
    "doc": 0.4,
    "people": [
      "Bimsara"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-04-06",
    "deadline": "2026-04-30",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "In Progress",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 32,
    "process": "QFD Billings / coding Smartsheet Automated Email Feedback Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-03-16",
    "deadline": "2026-03-25",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 30,
    "process": "QFD DCI Tracker Automated Email Feedback Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-03-25",
    "deadline": "2025-04-09",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 25,
    "process": "Scorecard Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 0.7,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-09-15",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "IQ",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 3,
    "process": "IOM Help Appeal Creation Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.35,
    "manual_fte": 0.15,
    "last_run_date": "2026-04-27",
    "last_run_count": 33,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 35,
    "process": "Soleil Surgery Center - Patient Financial Services Macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-05-22",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 20,
    "process": "US Neuro Medical Record Submission Automation",
    "data": {},
    "type": "Automation",
    "status": "To Do",
    "completion": 0,
    "doc": 0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 33,
    "process": "AM Neuro LLC -  Patient Financial Services macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-05-22",
    "deadline": "2026-05-05",
    "frequency": "Daily",
    "auto_fte": 0.25,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 31,
    "process": "QFD Medical Records Request Automated Email Feedback Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-03-25",
    "deadline": "2025-04-09",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 28,
    "process": "Heart Associate Reports Extractions",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-12-15",
    "deadline": "2025-12-16",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 26,
    "process": "Client Report Extraction Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 0,
    "people": [
      "Bimsara",
      "Shashani"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2024-05-13",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "IQ",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 10,
    "process": "QFD UHC Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.2,
    "manual_fte": 0.3,
    "last_run_date": "2026-05-01",
    "last_run_count": 509,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 43,
    "process": "Pre-Auth and VOB for All Clients",
    "data": {},
    "type": "Software Development",
    "status": "Pending",
    "completion": 0,
    "doc": 0,
    "people": [
      "Upcoming"
    ],
    "dept": null,
    "priority": null,
    "start_date": null,
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 38,
    "process": "QFD Automated Collection File Macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-12-01",
    "deadline": "2025-12-02",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 11,
    "process": "US Neuro UHC Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-05-01",
    "deadline": "2026-05-05",
    "frequency": "Monthly",
    "auto_fte": 0.4,
    "manual_fte": 2.0,
    "last_run_date": "2026-04-06",
    "last_run_count": 4254,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 44,
    "process": "Billing Application Prompts Billing Requirements",
    "data": {},
    "type": "Software Development",
    "status": "Pending",
    "completion": 0,
    "doc": 0,
    "people": [
      "Upcoming"
    ],
    "dept": null,
    "priority": null,
    "start_date": null,
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 9,
    "process": "QFD Paper Claims Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.05,
    "manual_fte": 0.2,
    "last_run_date": "2026-05-01",
    "last_run_count": 9,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 17,
    "process": "Integrity All Client Patient Smartsheet Stats Sharing Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.12,
    "manual_fte": null,
    "last_run_date": "2026-05-04",
    "last_run_count": 14,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 41,
    "process": "Heart Associates - Patient Financial Services Macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-08-13",
    "deadline": "2025-08-15",
    "frequency": "Daily",
    "auto_fte": 0.25,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 39,
    "process": "QFD Line Wise Output Collection File Macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-06-24",
    "deadline": "2025-06-25",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 8,
    "process": "QFD Medical Record Submission Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.1,
    "manual_fte": 0.1,
    "last_run_date": "2026-04-28",
    "last_run_count": 39,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 5,
    "process": "QFD Charge Import Billing Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 0.56,
    "manual_fte": 0.5,
    "last_run_date": "2026-05-05",
    "last_run_count": 102,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 12,
    "process": "TSH UHC Collection Engine",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.1,
    "manual_fte": 0.05,
    "last_run_date": "2026-05-01",
    "last_run_count": 5,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 6,
    "process": "QFD Medical Record Uploading Billing Automation",
    "data": {},
    "type": "Automation",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Daily",
    "auto_fte": 3.2,
    "manual_fte": 0.2,
    "last_run_date": "2026-05-04",
    "last_run_count": 214,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 45,
    "process": "Collective Website",
    "data": {},
    "type": "Software Development",
    "status": "Production",
    "completion": 0,
    "doc": 0,
    "people": [
      "Amandi"
    ],
    "dept": null,
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 1,
    "process": "TSH Medical Reporat Downlods",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-03-25",
    "deadline": "2026-04-13",
    "frequency": "One Time",
    "auto_fte": 6.0,
    "manual_fte": null,
    "last_run_date": "2026-05-01",
    "last_run_count": 3000,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 46,
    "process": "US Neuro MR & Appeal upload to SharePoint",
    "data": {},
    "type": "Automation",
    "status": "Developing",
    "completion": 0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-05-01",
    "deadline": "2026-05-05",
    "frequency": "Daily",
    "auto_fte": 0.25,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 42,
    "process": "Project Progress Dashboard",
    "data": {},
    "type": "Software Development",
    "status": "Enhancement",
    "completion": 1.0,
    "doc": 0,
    "people": [
      "Shashani"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-04-08",
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "A web based dashboard to track and manage the progress of automation and software developments across teams. Here showing status, development %, documentation %, and key metrics in one place.",
    "expected_results": "Teams can easily monitor all projects at a glance, manage tasks through meeting updates, milestones, requirements, change requests, feature add-ons, and bug fixes, while admins can add, edit, and maintain project data with real-time updates.",
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 16,
    "process": "TSH Patient Statement Automation",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": null,
    "deadline": null,
    "frequency": "Monthly",
    "auto_fte": 0.1,
    "manual_fte": 0.1,
    "last_run_date": "2026-03-11",
    "last_run_count": 143,
    "purpose": "Reduce manual FTEs and more efficient on the process flow",
    "expected_results": "Deploy the automation using RPA and Manual combination",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 40,
    "process": "QFD Patient Identifier Macro",
    "data": {},
    "type": "Automation",
    "status": "Production",
    "completion": 1.0,
    "doc": 1.0,
    "people": [
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2025-08-05",
    "deadline": "2025-08-12",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Integrity",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": []
  },
  {
    "id": 237,
    "process": "RCM Automation Common Platform",
    "data": {},
    "type": "Software Development",
    "status": "Developing",
    "completion": 0,
    "doc": 0,
    "people": [
      "Amila"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-05-01",
    "deadline": "2026-05-06",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [
      "Documentation"
    ],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 234,
    "process": "Unified Automation System",
    "data": {},
    "type": "Software Development",
    "status": "To Do",
    "completion": 0,
    "doc": 0,
    "people": [
      "Amila"
    ],
    "dept": null,
    "priority": null,
    "start_date": null,
    "deadline": null,
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [
      "Researching"
    ],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Pending",
    "assigned_ba": []
  },
  {
    "id": 236,
    "process": "Client Performance Monitoring System",
    "data": {},
    "type": "Software Development",
    "status": "Developing",
    "completion": 0.2,
    "doc": 0.3,
    "people": [
      "Shashani"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-05-04",
    "deadline": "2026-06-09",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "BI",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "In Progress",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 23,
    "process": "Collective IQ RCM Analytics Dashboard",
    "data": {},
    "type": "Software Development",
    "status": "Developing",
    "completion": 0.85,
    "doc": 0.7,
    "people": [
      "Bimsara",
      "Dilmi"
    ],
    "dept": "IQ",
    "priority": "High",
    "start_date": "2026-03-27",
    "deadline": "2026-05-05",
    "frequency": null,
    "auto_fte": null,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "The goal of this project is to build a centralized dashboard platform where our company can manage and monitor multiple clients from a single system. The application will have two main roles: an Admin role and a Client role.",
    "expected_results": "The system will support multiple clients including QFD, TSH, USNeuro, IOM Help, Soleil Surgery, TPC, Confidas, NTOS, Mind Sync, Synapses, Global Neurodiagnostic, Complete Neuro, Neuro Watch, and Innervate.",
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "In Progress",
    "assigned_ba": [
      "Imalsha"
    ]
  },
  {
    "id": 235,
    "process": "IOM Help Billing Automation",
    "data": {},
    "type": "Software Development",
    "status": "Pending",
    "completion": 0,
    "doc": 1.0,
    "people": [
      "Upcoming"
    ],
    "dept": null,
    "priority": null,
    "start_date": null,
    "deadline": "2026-05-05",
    "frequency": "Daily",
    "auto_fte": 0.25,
    "manual_fte": null,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": null,
    "expected_results": null,
    "beta_testing_date": null,
    "assign_team": "Software Development",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  },
  {
    "id": 19,
    "process": "QFD Medical Record Availability Check Automation",
    "data": {},
    "type": "Automation",
    "status": "Developing",
    "completion": 0.95,
    "doc": 1.0,
    "people": [
      "Piyum"
    ],
    "dept": "Automation",
    "priority": "High",
    "start_date": "2026-04-21",
    "deadline": "2026-04-30",
    "frequency": "Daily",
    "auto_fte": 0.15,
    "manual_fte": 0.05,
    "last_run_date": null,
    "last_run_count": null,
    "purpose": "Reduce manual FTEs and more efficient on the process flow.",
    "expected_results": "Deploy the automation using RPA and Manual combination.",
    "beta_testing_date": null,
    "assign_team": "Automation",
    "tags": [],
    "demo_video": null,
    "doc_note": "",
    "doc_status": "Complete",
    "assigned_ba": [
      "Chamath"
    ]
  }
];

async function main() {
  let ok = 0, skip = 0;
  for (const row of data) {
    try {
      await p.progress.upsert({
        where: { id: row.id },
        update: row,
        create: row,
      });
      ok++;
      console.log('OK ' + row.id + ' ' + row.process.substring(0, 50));
    } catch(e) {
      skip++;
      console.warn('SKIP ' + row.id + ' ' + e.message.substring(0, 80));
    }
  }
  console.log('Done -- ' + ok + ' imported, ' + skip + ' skipped');
}

main().catch(e => console.error('Fatal:', e.message)).finally(() => p.$disconnect());
