-- This migration was applied before Prisma migration tracking was set up.
-- The database already has all tables from the initial setup.
-- This file is a placeholder so Prisma's migration history stays in sync.
